// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var codeMirror, component, editor, editorInfo, editorInfos, mode, target, updateContent, _i, _len, _results;
    editorInfos = [
      {
        target: "#styles",
        mode: "text/css",
        editor: "#cssEditor",
        component: CssRenderer
      }, {
        target: "#html",
        mode: "text/html",
        editor: "#htmlEditor",
        component: HtmlRenderer
      }
    ];
    _results = [];
    for (_i = 0, _len = editorInfos.length; _i < _len; _i++) {
      editorInfo = editorInfos[_i];
      target = editorInfo.target, mode = editorInfo.mode, editor = editorInfo.editor, component = editorInfo.component;
      codeMirror = CodeMirror.fromTextArea($(editor)[0], {
        mode: mode
      });
      updateContent = function(content) {
        return React.renderComponent(new component({
          content: content
        }), $(target)[0]);
      };
      updateContent(codeMirror.getValue());
      _results.push(codeMirror.on("change", function(editor, change) {
        return updateContent(editor.getValue());
      }));
    }
    return _results;
  });

}).call(this);
