// Generated by CoffeeScript 1.6.3
(function() {
  window.HtmlRenderer = React.createClass({
    render: function() {
      return (new HtmlToRNodeParser()).htmlToRNode("<div>" + this.props.content + "</div>");
    }
  });

}).call(this);
