// Generated by CoffeeScript 1.6.3
(function() {
  var conn;

  conn = chrome.runtime.connect();

  conn.onMessage.addListener(function(message) {
    return chrome.runtime.sendMessage("pong");
  });

  chrome.devtools.inspectedWindow.onResourceContentCommitted.addListener(function(resource, content) {
    return chrome.runtime.sendMessage({
      url: resource.url,
      content: content
    });
  });

  chrome.devtools.inspectedWindow.onResourceAdded.addListener(function(resource) {
    return chrome.runtime.sendMessage({
      url: "ADD: " + resource.url
    });
  });

}).call(this);
