// Generated by CoffeeScript 1.6.3
(function() {
  chrome.browserAction.onClicked.addListener(function(tab) {
    return chrome.pageCapture.saveAsMHTML({
      tabId: tab.id
    }, function(mhtml) {
      var host, reader;
      host = "http://localhost:3000";
      reader = new FileReader();
      reader.addEventListener("loadend", function() {
        var arr, c, payload, _i, _len, _ref;
        arr = Array.prototype.map.call(reader.result.toString(), function(c) {
          return c.charCodeAt(0);
        });
        payload = "";
        _ref = deflate(arr);
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          c = _ref[_i];
          payload += String.fromCharCode(c);
        }
        return $.get("" + host + "/phorks/new", {}, function(response) {
          var mhtml_url, phork_id;
          mhtml_url = response.mhtml_url;
          phork_id = response.phork_id;
          return $.ajax({
            type: "PUT",
            contentType: "multipart/related",
            url: mhtml_url,
            data: payload,
            success: function(response) {
              return $.post("" + host + "/phorks", {
                phork_id: phork_id
              }, function(response) {
                return chrome.tabs.executeScript({
                  code: "document.location = '" + host + "/phorks/" + phork_id + "';"
                });
              });
            }
          });
        });
      });
      return reader.readAsText(mhtml);
    });
  });

}).call(this);
