// Generated by CoffeeScript 1.4.0
(function() {

  chrome.browserAction.onClicked.addListener(function(tab) {
    return chrome.pageCapture.saveAsMHTML({
      tabId: tab.id
    }, function(mhtml) {
      var reader;
      reader = new FileReader();
      reader.addEventListener("loadend", function() {
        var payload;
        payload = {
          mhtml: reader.result
        };
        return $.get("http://localhost:3000/phorks/new", JSON.stringify(payload), function(response) {
          var mhtml_url;
          mhtml_url = response.mhtml_url;
          return $.ajax({
            type: "PUT",
            contentType: "multipart/related",
            url: mhtml_url,
            data: payload.mhtml.toString(),
            success: function(response) {
              return console.log(response);
            }
          });
        });
      });
      return reader.readAsText(mhtml);
    });
  });

}).call(this);
